### ISSUE TITLE
Types of data and limits to HTML table

### ISSUE THREAD

**Issue by Bystroushaak** [edeposit/edeposit.amqp.rest#18]

**Comment by jstavel** [comment]
Ahoj Jardo, nasel jsem dokument, treba se Ti bude hodit.
https://plone.org/events/regional/past-events/nola05/collateral/Chris%20McDonough-ZODB%20Tips%20and%20Tricks.pdf

**Comment by jstavel** [comment]
a jeste toto: me to vrta v hlave.
http://grok.zope.org/doc/community/data_access/index_and_search_zodb.html

**Comment by Bystroushaak** [comment]
Ten prvni moc nepomohl, ten druhý vypadá zajímavěji, díky.
