### ISSUE TITLE
Design the architecture

### ISSUE THREAD

**Issue by Bystroushaak** [edeposit/edeposit.amqp.rest#3]
![scan](https://cloud.githubusercontent.com/assets/227282/10546352/bfd23c58-742d-11e5-84e2-1ef94bbb0958.png)

**Comment by jstavel** [comment]
To je pekne barevne! Sice to nema s vecnymi pripominkami nic spolecneho, ale vypada to pekne!

**Comment by Bystroushaak** [comment]
![asd](https://cloud.githubusercontent.com/assets/227282/11530061/ba8abe08-98f1-11e5-8488-f144b524f810.png)

**Comment by Bystroushaak** [comment]
Final version:

![architektura_e](https://cloud.githubusercontent.com/assets/227282/11532828/c147a106-9906-11e5-9b98-9418f7296892.png)
